# Copy a File to Remote Hosts

# Write a playbook to copy a local configuration file to /etc/ on all remote servers.

---
# linux server
- name: copy file playbook
  hosts: all
  gather_facts: no
  tasks: 
    - name: copying to remote server
      copy: 
        src: '/tmp/config.cnf'
        dest: '/etc/config.cnf'
        mode: '0644'
        owner: 'root'
        group: 'root'
      register: copy_status

    - debug:
        var: copy_status
      when: copy_status is defined

